info:
  profile: dev
  from: git

test: devaa
password: '{cipher}AQBkfGVRlxZjYjr1G/6tFeNkVdIGcHyK5Tm8Z0F/jgwxp1iP4Jf4P2enP/9bKnLgrNogk2LfooVdba3Icn1nyFj1rw5lfJVd60Uym84xNVTslkAkLW6EfkGE8nu8XTfUaIDZTZ+Ltu1Yv+p08d8kWtcNyaVZff3ncxCqGqBO1NJoVqzfI27MMEzL9+1kn6zfIrZjR+QreITWqzTr8SwACLCmAGr3dqaTi/ebBGUMukApBrlqxOPqq7yxL/m464m/qq3N9yj0+oZcvhXMuJBAVxyJm6nlizlq7is4UslPC3xsoojm+nJEBB2BTTjB4PhhcepkHfryjNJz42e6+zBZB694nkOqAVgJeRW9jGnGvOUJH8SdofKKSC7Mc+ZRrc5ledg='
